services:
  # Backend Service - Node.js API
  - type: web
    name: school-management-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://mhnazary2020:12345@cluster0.zze6col.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: FRONTEND_URL
        value: https://school-management-frontend.onrender.com
    healthCheckPath: /api/dashboard
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1

  # Frontend Service - React Static Site
  - type: web
    name: school-management-frontend
    env: static
    buildCommand: "cd frontEnd && npm install && npm run build"
    publishDirectory: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://school-management-backend.onrender.com
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
